<?php include __DIR__ . '/header.phtml'; ?>

<h2>Logo Inc.</h2>

<p>Odio ut sem nulla pharetra diam sit amet. Adipiscing elit duis tristique sollicitudin nibh. Blandit volutpat maecenas volutpat blandit aliquam. Non blandit massa enim nec. Ac ut consequat semper viverra nam. Platea dictumst vestibulum rhoncus est pellentesque. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. In hendrerit gravida rutrum quisque non tellus orci ac.</p>

<p><em>Learn more about Logo Inc. from <a href="/about">about</a></em></p>

<?php include __DIR__ . '/footer.phtml'; ?>